### ISSUE TITLE
genabout does not support writing to windows paths > 255 chars

### ISSUE THREAD

**Issue by tstephens619** [aboutcode-org/aboutcode-toolkit#143]
Windows, Python27
The genabout tool will trow an error if the .about file is being written to a filename/directory path that is > 255 characters.  The paths can become quite large. Is there any workaround for this?  

-Tim

**Comment by chinyeungli** [comment]
Potential solution:

http://stackoverflow.com/questions/14075465/copy-a-file-with-a-too-long-path-to-another-directory-in-python

**Comment by chinyeungli** [comment]
@tstephens619 I will need to discuss with @pombredanne to think of a correct solution for this issue. In the mean time, you can use Cygwin to run AboutCode to prevent this issue.

**Comment by pombredanne** [comment]
@chinyeungli @tstephens619 the issue is a windows issue more than a Python issue. The win32 api does not supports paths longer than 260 chars even though NTFS does. There are ways around it though, using some magic UNC prefix `\\?\` ... For instance this function handles it: https://bitbucket.org/jaraco/jaraco.windows/src/ad8bc62c0bba919ee4d8b8e42d133e09d6b41d64/jaraco/windows/filesystem/__init__.py?at=default#cl-79

So we have a way to deal with it alright. I will come up with a suggested implementation in the simplification branch sometimes next week.

**Comment by pombredanne** [comment]
Just for reference this is the bug in Python:
https://bugs.python.org/issue18199

**Comment by pombredanne** [comment]
@chinyeungli this bug has been fixed, right? if so please close

**Comment by chinyeungli** [comment]
Yes
