### ISSUE TITLE
The spec v0.8.1 does not match the v1.0 of the code for the about_file field

### ISSUE THREAD

**Issue by jdaguil** [aboutcode-org/aboutcode-toolkit#154]
When running genabout.py for v1.0 of the code the following message occurred when about_file was not in the input csv. 

Required keys not found.
('name', 'version', 'about_file')

However, the current version of the spec (http://www.dejacode.org/about_spec_v0.8.1.html) states:  
"2013.05.03: Renamed about_file to about_resource, and also made about_resource a mandatory field." The spec or the code needs to be updated so that the required key (about_file or about_resource) is clear.

**Comment by chinyeungli** [comment]
@jdaguil Perhaps we need to document what are the keys needed for different scripts/operation.
For instance, the document in the spec is basically for about.py and genabout.py (i.e. from ABOUT files to CSV or from CSV to ABOUT file), the 'about_file' is not needed in these 2 scripts because the tool will create the 'about_file' key. However, for the genattrib.py, the tool needs to know the 'about_file' location to get data form the ABOUT file to generate the attribution, and thus the 'about_file' is essential here.

**Comment by jdaguil** [comment]
@chinyeungli I think that would work. We should probably have a draft doc with the specific updates needed for the spec. I can push it once it is ready. On another note, when I ran genabout.py it would not create about files (and kept prompting the message Required keys not found.) until I had about_file in the input csv.

**Comment by chinyeungli** [comment]
@jdaguil Sorry, I was wrong.
The 'about_file' column is needed for ALL the scripts, but the 'about_resource' is not needed anymore.

**Comment by chinyeungli** [comment]
This is old. Open #342 for the overall review and closing this.
