### ISSUE TITLE
genabout.py input field about_file results in about_resource field in generated .ABOUT file

### ISSUE THREAD

**Issue by jdaguil** [aboutcode-org/aboutcode-toolkit#157]
When running genabout.py, the mandatory field **about_file** field maps to **about_resource** field in the corresponding generated .ABOUT file instead of the **about_file** field.

Currently:
**about_file** --> **about_resource**

Expected:
**about_file** --> **about_file**

Used v1 of code on 2014-10-30

**Comment by DennisClark** [comment]
Please also note that the spec, http://www.dejacode.org/about_spec_v0.8.1.html  still refers to "The mandatory "about_resource" field..."

**Comment by chinyeungli** [comment]
I agree there is a little bit confuse. Here is the story:
genabout.py:

The 'about_resource' is NOT required. This field will be generated based on the file type (based on the last character in the component path. If it ends with '/', we treat it as a directory, file otherwise). If it is a file, then the value of the 'about_resource' in the generated ABOUT file is <filename with extension>.ABOUT (such as test.c.ABOUT). If it is a directory, the value of the 'about_resource' in the generated ABOUT file is '.' (i.e referencing the whole directory)

Note that the user can provide the 'about_resource' field in the input CSV file. If 'about_resource' field detected in the input CSV and there is value in it, the above auto-generation for the 'about_resource' value will not be performed. However, if 'about_resource' key presents without value, the above 'about_resource' value generation will still process and overwrite the empty value.

Moreover, we don't need the 'about_file' key in the generated ABOUT file because it is basically the path of the 'about_file' which provide no information but confusion if user decide to move the ABOUT file around manually.

about.py

HOWEVER, in the about.py, the 'about_resource' field is REQUIRED.
As the tool extracts data from these ABOUT files, it will check the existence of the file/directory that the ABOUT file is referencing to.

The current spec was written based on the idea that we already have a set of ABOUT files and ready to extract data from these ABOUT files and output it to a CSV file. As a result, the 'about_resource' field is mandatory.

**Comment by chinyeungli** [comment]
Also, in the genabout.py, the 'about_file' is mandatory because it is required to tell the tool where should the ABOUT files be generated. However, in the about.py, the 'about_file' is NOT needed in the ABOUT file because it's basically the path location of the ABOUT file and will cause confusion if user move ABOUT files around manually.

**Comment by chinyeungli** [comment]
@DennisClark Does the above make sense?

**Comment by DennisClark** [comment]
This really a documentation issue.  USAGE.rst updated to clarify what genabout.py will do if you do not use --mapping option, and what it will do if you use it.  Closing.
