### ISSUE TITLE
about.py not locating resources that were generated by genabout.py

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/aboutcode-toolkit#200]
about-code-tool-2.0.2.  When I run about.py with input from a directory previously generated by genabout.py, i get multiple error messages with the following pattern, repeatedly: 

Field: about_resource, Value: AlphaIcon.java, Message: File does not exist.

It does not make sense that about.py cannot navigate the AboutCode files generated by genabout.py.  The two utiliities need to operate in a "round-trip" mode.

**Comment by chinyeungli** [comment]
@DennisClark the error is saying the file "AlphaIcon.java" doesn't not exist. It is not saying the AboutCode file.
This happens as the about.py will look at the context of the AboutCode file and look for the referenced file, AlphaIcon.java (in this case). Since the actual "AlphaIcon.java" doesn't exist, it gives error.

Let me know if this still doesn't make sense.

**Comment by DennisClark** [comment]
In that case, it should be a Warning, not an Error.

**Comment by chinyeungli** [comment]
Couple scenario that lead to this:
- The AboutCode file is useless and reference nothing which should not be put in the codebase.
- The AboutCode file is put/generated/created in the wrong place.
- The AboutCode file location is correct, but, for some reasons, somehow the actual file is missing or be renamed, or be moved to other places.

**Comment by chinyeungli** [comment]
The `about inventory` doesn't return any warning for the missing about_resource reference in ABOUT files.
