### ISSUE TITLE
Enhance genattrib.py and about.py to accept archive file input

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/aboutcode-toolkit#210]
This request is to enhance genattrib.py and about.py to accept an archive of AboutCode files as an alternative input instead of pointing to a directory.  

The use case is to make it easier for a development team (who does not embed AboutCode files inside their codebase) to keep a "portable" set of AboutCode files to use in Attribution generation, as well as make it easier to automate the various AboutCode steps.

The enhancement would be an option for genattrib.py and about.py to accept an archive of AboutCode files as input_path, extract that archive locally in the AboutCode installation and use that data for Attribution (or inventory generation) with the assumption that the Resource path in the component_list parameter will be relative to the archive file.

We should only need to support relatively simple single-level archive formats such as .tar. .zip, .7z or .xz because there is no logical requirement for multi-stage compression here.

**Comment by DennisClark** [comment]
Adding this feature should not have a negative impact on existing usages of genattrib.py ; that is, existing command line usages should not have to be changed unless they need to take advantage of this new feature.   With that in mind, perhaps this can be done before version 3; that possibility should be evaluated for practicality within current maintenance and development activities.

**Comment by chinyeungli** [comment]
I believe this should also apply to the about.py?

**Comment by mjherzog** [comment]
I agree

**Comment by DennisClark** [comment]
Ticket description updated to include about.py

**Comment by chinyeungli** [comment]
so.. is the new feature be like instead of having implement a new function for the extraction, the tool should be smart enough to identify is the input a directory or an archive. 
If it's an archive, the tool will extract the archive locally and then run the genattrib.py/about.py?

In another case, if it is an archive with no ABOUT files in it (the user accidentally select the wrong archive), the tool will still extract it locally and prompts error such that there is no ABOUT files?

**Comment by DennisClark** [comment]
Yes and yes.
