### ISSUE TITLE
Enhance genattrib.py to print date+time generated as well as user on output

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/aboutcode-toolkit#211]
The date and time generated, and the user that generated the output, would be useful to clearly communicate how recently the file was generated and who generated the output file.

A simple message at the end of the ouput would be sufficient; for example:  
This file was generated at {{date + time}} by {{user}}.

Note that a current workaround is to run a shell command such as the following immediately after running genattrib.py: 

echo "This file was generated on $(date +"%Y-%m-%d-%H%M%S") by $USER " >> {{output_path}} 

to append a line to the end of the just-generated attribution .html file.

**Comment by chinyeungli** [comment]
@DennisClark 
I think passing the time as a variable to the template is a better option than "hardcode" it to display in the code.
For instance, perhaps some users may not want to display the timestamp for some reasons, or they may want to put it on the top of the attribution doc instead of the bottom, or they want to have somekind of color or bold the timestamp etc...
so the user can have more control.
In addition, do we really want to display the $USER ? I don't think this is useful.
Please feel free to input your feedback.

**Comment by chinyeungli** [comment]
I think this can be closed.
