### ISSUE TITLE
Add JSON as supported format for storing inventories, etc

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#246]
This is often easier to handle than a set of ABOUT YAML files when they are not stored in the codebase and is a single file.

**Comment by chinyeungli** [comment]
@pombredanne can you provide a sample of what will the JSON input looks like?

**Comment by chinyeungli** [comment]
The JSON support represent both input and output

**Comment by mjherzog** [comment]
The use case is to store the ABOUT content in a file, rather than a set of files, to simplify use of an ABOUT.JSON file as a mini-database for recording the results of some analysis for a product release.
The record layout within the JSON file should be quite similar to its current ABOUT file layout.  We need to include optional fields, but not sure how to handle custom fields.

**Comment by chinyeungli** [comment]
> The use case is to store the ABOUT content in a file, rather than a set of files...

This is basically the same as the `inventory` command which store the ABOUT content in a CSV file.
Added support to output JSON format from `inventory` command.

**Comment by chinyeungli** [comment]
The next step is to add support to read JSON file to generate ABOUT files.

**Comment by chinyeungli** [comment]
JSON support for `inventory`, `gen`, and `attrib` are integrated.
