### ISSUE TITLE
Field track_changes is not a supported field and is ignored.

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/aboutcode-toolkit#338]
The `track_changes` field is part of the SPEC but having `track_changes: true` breaks the validation.
https://github.com/nexB/aboutcode-toolkit/blob/develop/SPECIFICATION.rst#optional-licensing-flag-fields

```
Running aboutcode-toolkit version 3.1.1
Checking ABOUT files...
INFO: dist/pip-18.0-py2.py3-none-any.whl.ABOUT: Field track_changes is not a supported field and is ignored.
Found 1 errors.
make: *** [valid] Error 1
```

**Comment by chinyeungli** [comment]
@tdruez it's because the model is using
```
('track_change', BooleanField()),
```
no `s` in the `change`

See https://github.com/nexB/aboutcode-toolkit/blob/develop/src/attributecode/model.py#L691

Now, the question is do you want me to update to `track_changes` in the code, or update the spec doc?
I think updating the doc is a better approach as all the fields in the code are singular, but I am open with either option.

**Comment by tdruez** [comment]
@chinyeungli We added this field in the DejaCode database based on the SPEC `track_changes`.
I'm in favor of updating the code rather than the SPEC.
