### ISSUE TITLE
Clarify or remove "about_file_path" attribute

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#364]
When creating About object `location`  and `about_file_path` are required. It is not clear how both relate to the other and why the `about_file_path` would be needed

**Comment by pombredanne** [comment]
See also #289 as this may be a dupe

**Comment by chinyeungli** [comment]
@pombredanne The `about_file_path` is used to tell the tool where should the ABOUT file be generated.

**Comment by pombredanne** [comment]
@chinyeungli ack. Still this would only be useful if you needed to create a file in a non standard location

**Comment by chinyeungli** [comment]
@pombredanne I think the confusion here is `about_file_path` VS `about_resource`
In the input, we usually use `about_file_path` to indicate where should the ABOUT file be created such as `/abouts/project/a/b/c.ABOUT` and use the `about_resource` for the resource name i.e. `c.ABOUT`

However, since the `about_resource` is a `AboutResourceField(PathField)`, we should use the `about_resource` as a "path indicator" instead of using `about_file_path`

Is this your point?

**Comment by chinyeungli** [comment]
@DennisClark what do you think about this removal?
@pombredanne If we have 3 same components in the codebase, 
For instance,
```
/project/common-logging-1.1.tar.xz
/project/A/common-logging-1.1.tar.xz
/project/test/B/common-logging-1.1.tar.xz
```
We'll want to generate 3 ABOUT files side by side with the above 3 location instead of just generate 1 ABOUT file at `/project/` to reference the above 3 components?

**Comment by DennisClark** [comment]
The `about_file_path` value gives the `gen` user the ability to control where the output goes; that seems rather important to me, especially since I might want to specify a meaningful name for the primary directory that all of the generated files are going to go into.  I really don't understand why we would want to remove this. 

@chinyeungli  In your `/project/` example, that all makes sense, but it totally depends on the availability of the codebase itself, doesn't it?  And that has not been a use case that I have ever needed.  We need to make sure that we don't break our most common process. 

The existing  `about_file_path` design would still allow me to put stuff directly into the codebase, i think, simply by specifying the desired path values.  So I don't understand the need or advantage of changing this.

**Comment by chinyeungli** [comment]
There are 3 fields which are required when creating an ABOUT object.
```
class About(object):
    """
    Represent an ABOUT file and functions to parse and validate a file.
    """
    # special names, used only when serializing lists of ABOUT files to CSV or
    # similar

    # name of the attribute containing the relative ABOUT file path
    ABOUT_FILE_PATH_ATTR = 'about_file_path'

    # name of the attribute containing the resolved relative Resources paths
    about_resource_path_attr = 'about_resource_path'

    # Required fields
    required_fields = [ABOUT_FILE_PATH_ATTR, 'name']

    def get_required_fields(self):
        return [f for f in self.fields if f.required]

    def set_standard_fields(self):
        """
        Create fields in an ordered dict to keep a standard ordering. We
        could use a metaclass to track ordering django-like but this approach
        is simpler.
        """
        self.fields = OrderedDict([
            ('about_resource', AboutResourceField(required=True)),
            ('name', SingleLineField(required=True)),
```

The required fields are
1. `about_file_path`
2. `name`
3. `about_resource`

Purpose:
1. The `about_file_path` field is used to identify where the ABOUT file will be created (in `gen`) or where the ABOUT file is (in `inventory`)
2. The `name` can be the name of the resource or a component name based on user's input.
3. The `about_resource` identify which resource(s) is/are the ABOUT file referencing. i.e. it can be the name of the file or `.` to represent the current directory.

**Comment by chinyeungli** [comment]
@pombredanne 
I've been thinking about this again.

Here is what I am thinking:

Let say I have an input CSV named "input.csv" that contains 2 columns:
```
about_resource, name
/a/b/c/test.c, test.c
```

In the gen process, I will do
```
about gen input.csv ~/about/
```

Then the ~/about/a/b/c/test.c.ABOUT will be created.


After that, if I want to get an inventory, I will do
```
about inventory ~/about/ output.csv
```

The output.csv should be exactly the same as the input.csv as shown above.

In another word, there will be *NO* reference about the .ABOUT file in the generated inventory.
Is this the idea?

**Comment by chinyeungli** [comment]
The `about_file_path` is no longer needed/produced from the input and/or output although the code still have `about_file_path` attrib to identify where should the ABOUT file be generated
