### ISSUE TITLE
Primary Requirement:  generate attribution without an inventory 

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/aboutcode-toolkit#373]
from @mjherzog
We need a plan for how to run about attrib without an inventory input file telling you which packages to include in an Attribution Notice. One approach could be to require AbC TK to recognize fields like attribute: yes and internal_use_only: no, but I can also easily see why we would not want to "hard-code" this, especially since ABOUT fields are customizable.

**Comment by DennisClark** [comment]
[sample-attribution-workfiles.zip](https://github.com/nexB/aboutcode-toolkit/files/2605128/sample-attribution-workfiles.zip)

The attached zip contains the file `sample-attribution.template` that demonstrates how to use the template language Jinja2 to filter the ABOUT files in a codebase so that only the components that require attribution are selected for the output when running the about `attrib` option.   A sample mapping.config file is also included to illustrate how to specify the key fields desired to support the filtering process.

**Comment by DennisClark** [comment]
Generating attribution without an inventory can be accomplished using the Jinja2 code in the attribution template.  Successfully tested. Closing this issue.
