### ISSUE TITLE
Does not work with UTF-8 encoded .CSV input files

### ISSUE THREAD

**Issue by OctagonHex** [aboutcode-org/aboutcode-toolkit#432]
The current Excel version allow to export as UTF-8 encoded .CSV files.
This will put an Byte-Order-Marker (0xEF 0xBB 0xBF) as the first character in the file. 

Please allow for Byte-Order-Marker in .csv file and maybe also allow full UTF-8 support. 
Or if UTF-8 is not possible, Make the error message clearer. I wasted 1-2 hours for this.

The error is:
```
Generating .ABOUT files...
Command completed with 1 errors or warnings.
CRITICAL: The essential field 'about_resource' is not found in the <input>
```

Excel allows you to export as ANSI coded .CSV but it is further down the list...

**Comment by chinyeungli** [comment]
@OctagonHex Sorry for the confusion. Would you mind attaching your UTF-8 encoded CSV file and I will look into this.
Thanks in advance.

**Comment by chinyeungli** [comment]
@OctagonHex I've tried with the UTF-8 encoded CSV file, but I don't encounter a problem.
Here is my sample:

**test-utf8.csv**
```
about_resource,name,version,Category,Confirmed_License,dje_license_key,attribute,redistribute,track_changes,owner
/myFile,名,1,proprietary,,,yes,no,yes,Company
```

The `file` command shows this file is in UTF-8 format:
```
xxxxx:/xxxxxxxxx$ file test-utf8.csv
test-utf8.csv: UTF-8 Unicode text, with CRLF line terminators
```

Run the `about gen`
```
(aboutcode-toolkit) C:\xxx\git\aboutcode-toolkit>about gen C:\xxx\Desktop\tmp\432\test-utf8.csv C:\xxx\Desktop\tmp\432\out
C:\xxx\git\aboutcode-toolkit\\bin\about   gen C:\xxx\Desktop\tmp\432\test-utf8.csv C:\xxx\Desktop\tmp\432\out
Running aboutcode-toolkit version 4.0.2
Generating .ABOUT files...
1 .ABOUT files generated in C:\xxx\Desktop\tmp\432\out.
(aboutcode-toolkit) C:\xxx\git\aboutcode-toolkit>
```

Here is my **output**
```
# Generated with AboutCode Toolkit Version 4.0.2 

about_resource: myFile
name: 名
version: 1
redistribute: no
attribute: yes
track_changes: yes
owner: Company
category: proprietary
```

It'll be great if you can provide the problematic file so that I can dig deeper.
Thanks in advance.

**Comment by OctagonHex** [comment]
Yes, I attach an example. The file was exported from exportet from Excel 365 (version 1908) using the CSV UTF-8 file format in the save as dialog.

You did not see the problem in your file, because it is most likely missing the Byte-Order-Marker at the beginning, but contains the UTF-8 only in the data.

```
about gen test_utf8.csv .\outputDir

Running aboutcode-toolkit version 4.0.2
Generating .ABOUT files...
Command completed with 1 errors or warnings.
CRITICAL: The essential field 'about_resource' is not found in the <input>
0 .ABOUT files generated in C:\...\...\...\OutputDir.
```

[test_utf8.csv.txt](https://github.com/nexB/aboutcode-toolkit/files/5032692/test_utf8.csv.txt)

**Comment by chinyeungli** [comment]
@OctagonHex Thanks for sample. The issue is related to the Microsoft's UTF-8 variant (See https://docs.python.org/3/library/codecs.html#module-encodings.utf_8_sig)
I've updated the code to use encoding='utf-8-sig' and it should fix the issue.

The fix is pushed to the develop branch and will be push to the new release later.
