### ISSUE TITLE
Consider how scanpipe would fit into attributecode usage for more complex input

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/aboutcode-toolkit#498]
Consider how scanpipe would fit into attributecode usage for more complex input
* filter out noise
* prepare the input

**Comment by mjherzog** [comment]
For the direct Scan to Attribution workflow we need a way for a customer to filter the Scan results in order to produce a useful Attribution Notice. Some examples of criteria to reduce noise and volume are:
- License Score threshold
- Source code files only
- Packages only
These filter could be numerous and complex for large codebases so we should avoid overloading AttributeCode with this functionality, especially since many of these filters would also be relevant for streamlining Scan data into an Inventory or BOM. This should be a job for ScanPipe on ScanCode.io - if your codebases and Scans are large and complex you will need ScanPipe and ScanCode.io anyway.

**Comment by chinyeungli** [comment]
All these filtering, is likely, can be done via the template as long as the input has the proper fields to indicate if it's a package, source file etc...
