### ISSUE TITLE
Update README.rst for the genabout.py

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/aboutcode-toolkit#52]
The current README only describes the syntax and requirement for the about.py. We do have the genabout.py now and want the README to include information about this script.

**Comment by tdruez** [comment]
We should instead create proper documentation for each module.
A docs/ folder was created as a location for the documentation.
Eventually, the documentation will be publish on a service like https://readthedocs.org/ along pypi releases.

The README should point the documentation and maybe contains some simple usage examples rather than the full documentation of each commands.

**Comment by chinyeungli** [comment]
Closing this as we have the https://github.com/nexB/aboutcode-toolkit/blob/develop/USAGE.rst
